name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  osv-scan:
    name: OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanned-action

      - name: Upload OSV scan report to Security Dashboard
        uses: github/codeql-action/upload-sarif
        with:
          sarif_file: results.sarif 

  semgrep-scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@

      - name: Run Semgrep analysis for Java
        run: semgrep --config p/java --sarif -o semgrep-report.sarif

      - name: Upload Semgrep report to Security Dashboard
        uses: github/codeql-action/upload-sarif
        with:
          sarif_file: semgrep-report.sarif

